name: dbcicd37
channels:
  - conda-forge
dependencies:
  - python=3.7
  - wheel
  - pytest
  - setuptools
  - databricks-cli
  - azure-cli-core
  - azure-storage-blob
  - azure-identity
  - pyspark
  - python-decouple
  - findspark